# Generated by Django 3.1.2 on 2020-10-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0004_auto_20201028_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='StudentNumber',
            field=models.FloatField(max_length=20),
        ),
    ]
