# Generated by Django 3.1.2 on 2020-10-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0005_auto_20201028_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='StudentNumber',
            field=models.IntegerField(),
        ),
    ]
