# Generated by Django 3.1.2 on 2020-10-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0006_auto_20201028_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Money',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='StudentNumber',
            field=models.IntegerField(null=True),
        ),
    ]
