# Generated by Django 3.1.2 on 2020-10-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0007_auto_20201028_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
