# Generated by Django 3.1.2 on 2020-11-02 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0010_auto_20201031_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trytest.dishes')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trytest.user')),
            ],
        ),
    ]
