# Generated by Django 3.1.2 on 2020-11-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0012_user_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalUserLike',
            fields=[
                ('Data', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
