# Generated by Django 3.1.2 on 2020-11-03 13:14

from django.db import migrations, models
import trytest.models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0013_proposaluserlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesimage',
            name='DishPic',
            field=models.ImageField(null=True, upload_to=trytest.models.load_dishes_image),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='PStatus',
            field=models.CharField(max_length=10),
        ),
    ]
