# Generated by Django 3.1.2 on 2020-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0014_auto_20201103_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='TStatus',
            field=models.CharField(max_length=10),
        ),
    ]
