# Generated by Django 3.1.2 on 2020-11-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0015_auto_20201106_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trytest.user'),
        ),
    ]
