# Generated by Django 3.1.2 on 2020-11-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0017_auto_20201124_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='DishCategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trytest.category'),
        ),
    ]
