# Generated by Django 3.1.2 on 2020-12-08 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0019_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradecomment',
            name='Trade',
        ),
        migrations.AddField(
            model_name='tradecomment',
            name='TradeDish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trytest.tradedish'),
        ),
    ]
