# Generated by Django 3.1.2 on 2020-12-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0020_auto_20201208_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedish',
            name='CommentNum',
            field=models.IntegerField(default=0),
        ),
    ]
