# Generated by Django 3.1.2 on 2020-12-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0024_auto_20201208_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='CloseTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='OrderTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
