# Generated by Django 3.1.2 on 2020-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0025_auto_20201208_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradecomment',
            name='ReplyTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradecomment',
            name='ReplyId',
            field=models.IntegerField(null=True),
        ),
    ]
