# Generated by Django 3.1.2 on 2020-11-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0016_auto_20201106_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trytest.user'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='DishCategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trytest.category'),
        ),
    ]
