# Generated by Django 3.1.2 on 2020-11-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trytest', '0018_auto_20201124_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='DishCategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trytest.category'),
        ),
    ]
